### ISSUE TITLE
 Tetromino main functions

### ISSUE THREAD

**Issue by PashaBeshchuk** [PashaBeshchuk/tetris#24]
### Init function
This function should be invoked immediately on js load from separate script file init.js

Parameters:
- No parameters

Returns:
- Nothing

Algorithm:

- Init local variable size of field - object x,y fieldSize
- Create tetris class object via constructor new Tetris(object x,y fieldSize)
- Invoke every 1 second tick function on created tetris object with setTimeout 
- Register keyboardHandler to handle all “keydown” events 

### Function keyboardHandler
This function should be defined inside init function

Parameters:
- Keyboard event

Return:
- Nothing

Algorithm:
- If left button was pressed - tetris.moveLeft
- If right button was pressed - tetris.moveRight
- If down button was pressed - tetris.moveDown
- If up button was pressed - tetris.rotate
### Class Tetris

Properties:
- tetrominoTypes
- fieldSize
- tetromino
- field

**_Constructor_**

Parameters:
- object x,y fieldSize

Algorithm:
- Init property tetrominoTypes from list of possible tetrominoes (example: [“L”, “S”, … ])
- Init property fieldSize from constructor parameter
- Create tetromino via function createTetromino(object x,y fieldSize, array tetrominoTypes)
- Init property tetromino
- Create field via new Field(object x,y fieldSize)
- Init property field

**Function tick**

Parameters:
- No parameters

Returns:
- Nothing

Algorithm:
- Check tetromino.canMoveDown()
- shift = {x: 0, y: 1}
- If true, tetromino.moveTetromino(this.field, shift)
- If false, field.addTetrominoToField(this.tetromino.coordinates)
- If false, create new tetromino via createTetromino, assign to local tetromino
- If false, field.cleanFilledRows()

**Function moveLeft**

Parameters:
- No parameters

Returns:
- Nothing

Algorithm:
- tetromino.moveTetromino(this.field.field, {x: -1, y: 0})

**Function moveRight**

Parameters:
- No parameters

Returns:
- Nothing

Algorithm:
- tetromino.moveTetromino(this.field.field, {x: 1, y: 0})

**Function moveDown**

Parameters:
- No parameters

Returns:
- Nothing

Algorithm:
- tetromino.moveTetromino(this.field.field, {x: 0, y: 1})

**Function rotate**
Parameters:
- No parameters

Returns:
- Nothing

Algorithm:
- tetromino.rotateTetromino(this.field.field)

### Class Tetromino

We need to add one more function to the class
**Function canMoveDown**

Function checks, the field for the next step is free or have elements, or it's bottom the field.

Parameters:
- boolean array (field)

Return:
- Boolean (example "false" or “true”)

Algorithm:
- Init variable shift = {x: 0, y: 1}
- let shiftTetrominoResult = module.exports.shiftCoordinates(this.coordinates, shift)
- Return module.exports.checkThatTheFieldIsFree(shiftTetrominoResult, field)
	
### Other module functions

**Function createTetromino**

Parameters:
- object x,y fieldSize
- array tetrominoTypes

Return:
- new tetromino

Algorithm:
- Get random element from tetromino types (typeOfTetromino)
- Get initial phase via startingPhaseOfTetromino (rotationPhase)
- Get initial coordinates via initCoordinates (coordinates)
- Call constructor new Tetromino(typeOfTetromino, rotationPhase, coordinates)

**Function startingPhaseOfTetromino**
This function determines the tetromino phase dependent on the tetromino type.

Parameter:
- string (as example “S")

Return:
- string (as example "up")

Algorithm: 
- S - horizontal
- Z - horizontal
- I - vertical
- J - left
- T - up
- L - right

**Function initCoordinates**
Must initialize coordinates in specific initial phase for a particular type of tetromino. Must be as the middle top portion of the field

Parameter:
- Type tetromino
- object x,y fieldSize

Return:
- Array coordinates tetromino

Algorithm: 
- Сalculate the middle of the field
- depending on the type and position of the tetromino, add as much as possible to the center
- depending on the tetromino type, start counting from the axis y -1

**Comment by zbstof** [comment]
1 English only
2 specify algorithm for all functions 
3 Format properly (google gfm)

**Comment by PashaBeshchuk** [comment]
2 specify algorithm for all functions - I did this, what else do I have to write?)
3 Format properly (google gfm) - I did not find the answer on this

**Comment by zbstof** [comment]
canIMoveOn - gwhat is the exact algorithm?
Funciton checks, can I move on or I can't - rhis is not detailed enough

**Comment by zbstof** [comment]
Tetromino add in the field "(coordinatesOfTetromino)"
When this tetromino is created? Where addTetrominoToField is coming from? Object? When object is created?

**Comment by zbstof** [comment]
> Add event rotate tetromino
So what is the event? 
> If line on the field full we should remove this line and add new line cleanFilledRows()
We don't need to check anything

**Comment by zbstof** [comment]
> Tetromino add in the field "addTetrominoToField(coordinatesOfTetromino)"

Where is this done? this should be invoked once? Then write initialization function and do it there. Describe all initialization steps as algorithm for this function.

> Tetromino move down Function moveTetrominoDown

When is this done? Magically? Check how this is done in snake, if you forgot.

> When we trigger an event, the tetramino rotates Add event rotate tetromino

Describe exactly what event is triggered, what function is invoked, what are the inputs

> tetramino

typo, fix everywhere

> canIMoveOn

typo, fix everywhere

> When tetromino reaches the bottom or tetromino reaches elements in the fied Function canIMoveOn

This is part of algorithm, this should be in the function description, and not where you've put it. Where is the description?

> When tetromino reaches the bottom or tetromino reaches elements in the fied Function canIMoveOn:, we should add new elements for field Function addNewElementForField:, remove class Tetromino Function deleteTetrominoOnTheField: and add new tetromino on the field ** Function addTetrominoOnTheField:**.

What this algorithm is doing in the general section? This is algorithm of some function - describe this function separately.

> If line on the field full we should remove this line and add new line cleanFilledRows()

We don't need to check anything

> startingPhaseOfTetromino

This function is used in createTetramino - where does function createTetramino is used? If it is not used anywhere, remove it and startingPhaseOfTetromino. For each function there should be a place where it is invoked, otherwise it should not be there at all.
Also, if you are writing an examples, like `string ("S")`, then you should specify that "S" is an example, not actual parameter

> determineTypeTetromino

same as with startingPhaseOfTetromino
Also, mark `"J" or "S"` as examples

> createTetramino

see startingPhaseOfTetromino

> Paramets

typo, fix everywhere

> propertise

typo, fix everywhere

> new tetramino

What is new tetromino? Object? Array? Please specify type

> Function createField

where is it used?

> odj{x,y} or string---

What is this? Fix typos and formatting, also check that formatting is fine in the whole document. Refer to Github-flavored markdown (GFM) for reference: https://www.google.com/search?q=GFM&oq=GFM
All code should be marked as code to be properly displayed

> new field

What is this? Size? Type? Array or Object? Be specific 

> Function moveTetrominoDown

Why there's no separate algorithm section?
Why you are not re-using shift function in Tetromino class?
Move the whole function to tetromino class (specify requirement, do not write code yet)

> (sTetromino.coordinates)

Mark as example

> Function thePathOfContingentIsFree

Strange name. Use another word for `Contingent`
Move the whole function to tetromino class (specify requirement, do not write code yet)

> Funciton

typo

> dow

typo

> booline

typo

> (try or false)

typo

> calss Field

typo

> I should think this question

What is this doing here?

> function return or shift left or right

**Comment by zbstof** [comment]
`FInal function #24`

Rewrite the name of the issue - this is not only the functions that you are implementing
Also don't presume this is final - you don't have the UI yet

**Comment by zbstof** [comment]
Fix nesting of the headers - use "Preview" button when you edit.
